export const routes = {
  login: "/(auth)/login",
  dashboard: "/(tabs)/dashboard",
  inventory: "/(tabs)/inventory",
  products: "/(tabs)/products",
  reports: "/(tabs)/reports",
  settings: "/(tabs)/settings",
  attributes: "/protected/attributes",
  categories: "/protected/categories",
  devDatabase: "/protected/dev-database",
  newInventoryProducts: "/protected/new-inventory-products",
  revenuesExpenses: "/protected/revenues-expenses",
  units: "/protected/units",
  workersManagement: "/protected/workers-management",
  unauthorized: "/protected/unauthorized",
} as const;
