export const routes = {
  login: "/(auth)/login",
  dashboard: "/(tabs)/dashboard",
  inventory: "/(tabs)/inventory",
  finance: "/(tabs)/finance",
  invoices: "/(tabs)/invoices",
  reports: "/(tabs)/reports",
  inventoryLists: "/protected/inventory-lists",
  newInventoryList: "/protected/new-inventory-list",
  products: "/protected/products",
  productSettings: "/protected/product-settings",
  settings: "/protected/settings",
  attributes: "/protected/attributes",
  categories: "/protected/categories",
  devDatabase: "/protected/dev-database",
  newInventoryProducts: "/protected/new-inventory-products",
  units: "/protected/units",
  workersManagement: "/protected/workers-management",
  unauthorized: "/protected/unauthorized",
} as const;
